[build]
  # Your frontend code is inside the FRONTEND folder
  base = "FRONTEND"

  # Command to build your React frontend
  command = "npm run build"

  # Directory to publish after build (Vite outputs to dist)
  publish = "FRONTEND/dist"

  # Directory where Netlify will look for serverless functions
  functions = "FRONTEND/netlify/functions"

[build.environment]
  # Add your environment variables here
  VITE_BACKEND_URL = "https://converstum.onrender.com"
  VITE_SOCKET_SERVER_URL = "wss://converstum.onrender.com"

# Optional: redirect all routes to index.html for SPA behavior
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
